#!/usr/bin/env bash
# ============================================================================
# push-to-github.sh
# Pushes the Contentful-driven resources changes (and prior flight-trail
# work, if not yet pushed) to Admin0TSP/the-seo-pilot-site.
#
# Run this from your Mac terminal:
#   bash /Users/shipsy/Downloads/seo-pilot-site/seo-pilot-site/push-to-github.sh
#
# What it does:
#   1. Clones the remote repo into ~/Downloads/the-seo-pilot-site-clone
#      (creates the folder; safe if it already exists — it'll re-pull)
#   2. Copies the changed files in:
#        - flight-trail.css        (hero/scroll chrome)
#        - flight-trail.js
#        - index.html              (homepage hook wiring)
#        - resources-design.css    (NEW: resources/blog/case-study aesthetic)
#        - scripts/generate-resources.js  (Contentful → static HTML generator)
#        - resources/index.html              (re-designed hub)
#        - resources/blog/index.html         (re-designed blog placeholder)
#        - resources/case-studies/index.html (re-designed case-study placeholder)
#   3. Removes the old hardcoded Aspora case study folder from the clone
#      (case studies are now 100% Contentful-driven).
#   4. Commits and pushes to main.
#
# Prereqs: git installed, and you're authenticated to GitHub for the repo
#   (either via the GitHub CLI `gh auth login`, an SSH key, or an HTTPS PAT
#    cached via osxkeychain).
# ============================================================================

set -euo pipefail

LOCAL_SITE="/Users/shipsy/Downloads/seo-pilot-site/seo-pilot-site"
CLONE_DIR="$HOME/Downloads/the-seo-pilot-site-clone"
REPO_URL="https://github.com/Admin0TSP/the-seo-pilot-site.git"
BRANCH="main"
COMMIT_MSG="${COMMIT_MSG:-Sync site updates to main}"

# ---------------------------------------------------------------------------
# 1. Clone (or refresh) the remote repo locally
# ---------------------------------------------------------------------------

echo "==> Cloning $REPO_URL into $CLONE_DIR"
if [ -d "$CLONE_DIR/.git" ]; then
  echo "    Clone already exists — pulling latest."
  git -C "$CLONE_DIR" checkout "$BRANCH"
  git -C "$CLONE_DIR" pull --ff-only origin "$BRANCH"
else
  git clone "$REPO_URL" "$CLONE_DIR"
  git -C "$CLONE_DIR" checkout "$BRANCH"
fi

DEST="$CLONE_DIR/seo-pilot-site"

# ---------------------------------------------------------------------------
# 2. Copy the changed files into the clone
# ---------------------------------------------------------------------------

echo "==> Copying changed files into the clone"

# Make sure target subdirs exist
mkdir -p "$DEST/scripts" \
         "$DEST/resources/blog" \
         "$DEST/resources/case-studies"

# Flight-Trail (homepage chrome) — copy only if present locally
[ -f "$LOCAL_SITE/flight-trail.css" ] && cp "$LOCAL_SITE/flight-trail.css" "$DEST/flight-trail.css"
[ -f "$LOCAL_SITE/flight-trail.js"  ] && cp "$LOCAL_SITE/flight-trail.js"  "$DEST/flight-trail.js"
[ -f "$LOCAL_SITE/index.html"       ] && cp "$LOCAL_SITE/index.html"       "$DEST/index.html"

# Global stylesheet (nav submenu CSS lives here)
cp "$LOCAL_SITE/style.css"                       "$DEST/style.css"

# Resources design + generator
cp "$LOCAL_SITE/resources-design.css"            "$DEST/resources-design.css"
cp "$LOCAL_SITE/scripts/generate-resources.js"   "$DEST/scripts/generate-resources.js"

# Contentful push pipeline + GSC indexing pipeline
cp "$LOCAL_SITE/scripts/push-to-contentful.js"   "$DEST/scripts/push-to-contentful.js"
cp "$LOCAL_SITE/scripts/markdown-to-richtext.js" "$DEST/scripts/markdown-to-richtext.js"
cp "$LOCAL_SITE/scripts/index-urls.js"           "$DEST/scripts/index-urls.js"
cp "$LOCAL_SITE/scripts/regenerate-sitemap.js"   "$DEST/scripts/regenerate-sitemap.js"
cp "$LOCAL_SITE/package.json"                    "$DEST/package.json"
cp "$LOCAL_SITE/.env.example"                    "$DEST/.env.example"
cp "$LOCAL_SITE/.gitignore"                      "$DEST/.gitignore"
mkdir -p "$DEST/docs"
[ -f "$LOCAL_SITE/docs/GSC-INDEXING-SETUP.md" ] && cp "$LOCAL_SITE/docs/GSC-INDEXING-SETUP.md" "$DEST/docs/GSC-INDEXING-SETUP.md"
[ -f "$LOCAL_SITE/docs/NEW-LAPTOP-SETUP.md"   ] && cp "$LOCAL_SITE/docs/NEW-LAPTOP-SETUP.md"   "$DEST/docs/NEW-LAPTOP-SETUP.md"

# Brand logos for the trusted-by marquee
if [ -d "$LOCAL_SITE/assets/img/brand-logos" ]; then
  mkdir -p "$DEST/assets/img/brand-logos"
  cp -R "$LOCAL_SITE/assets/img/brand-logos/." "$DEST/assets/img/brand-logos/"
fi

# sitemap.xml — regenerated by `npm run update-sitemap`
[ -f "$LOCAL_SITE/sitemap.xml" ] && cp "$LOCAL_SITE/sitemap.xml" "$DEST/sitemap.xml"

# Site hygiene / PWA / hosting files
# - 404.html: custom branded 404 page
# - manifest.webmanifest: PWA manifest (theme color + icons)
# - apple-touch-icon.png: iOS home-screen icon (180x180)
# - render.yaml: hosting config (security headers — HSTS, CSP, etc.)
# - robots.txt + _redirects: crawl + redirect rules
[ -f "$LOCAL_SITE/404.html"               ] && cp "$LOCAL_SITE/404.html"               "$DEST/404.html"
[ -f "$LOCAL_SITE/manifest.webmanifest"   ] && cp "$LOCAL_SITE/manifest.webmanifest"   "$DEST/manifest.webmanifest"
[ -f "$LOCAL_SITE/apple-touch-icon.png"   ] && cp "$LOCAL_SITE/apple-touch-icon.png"   "$DEST/apple-touch-icon.png"
[ -f "$LOCAL_SITE/render.yaml"            ] && cp "$LOCAL_SITE/render.yaml"            "$DEST/render.yaml"
[ -f "$LOCAL_SITE/robots.txt"             ] && cp "$LOCAL_SITE/robots.txt"             "$DEST/robots.txt"
[ -f "$LOCAL_SITE/_redirects"             ] && cp "$LOCAL_SITE/_redirects"             "$DEST/_redirects"

# Content folder (markdown case studies + README)
mkdir -p "$DEST/content/case-studies" "$DEST/content/blog"
[ -f "$LOCAL_SITE/content/README.md" ] && cp "$LOCAL_SITE/content/README.md" "$DEST/content/README.md"
for md in "$LOCAL_SITE/content/case-studies"/*.md; do
  [ -f "$md" ] && cp "$md" "$DEST/content/case-studies/"
done
for md in "$LOCAL_SITE/content/blog"/*.md; do
  [ -f "$md" ] && cp "$md" "$DEST/content/blog/"
done

# Re-designed listing/hub placeholders + nav-submenu on every page that has a navbar
cp "$LOCAL_SITE/resources/index.html"                "$DEST/resources/index.html"
cp "$LOCAL_SITE/resources/blog/index.html"           "$DEST/resources/blog/index.html"
cp "$LOCAL_SITE/resources/case-studies/index.html"   "$DEST/resources/case-studies/index.html"

# Other pages that also got the nav-submenu update
mkdir -p "$DEST/privacy" "$DEST/terms" "$DEST/blog-preview"
[ -f "$LOCAL_SITE/privacy/index.html"       ] && cp "$LOCAL_SITE/privacy/index.html"       "$DEST/privacy/index.html"
[ -f "$LOCAL_SITE/terms/index.html"         ] && cp "$LOCAL_SITE/terms/index.html"         "$DEST/terms/index.html"
[ -f "$LOCAL_SITE/blog-preview/index.html"  ] && cp "$LOCAL_SITE/blog-preview/index.html"  "$DEST/blog-preview/index.html"

# ---------------------------------------------------------------------------
# 3. Remove the hardcoded Aspora case study (now lives in Contentful)
# ---------------------------------------------------------------------------

if [ -d "$DEST/resources/case-studies/aspora-ai-visibility" ]; then
  echo "==> Removing hardcoded /resources/case-studies/aspora-ai-visibility/"
  git -C "$CLONE_DIR" rm -rf "seo-pilot-site/resources/case-studies/aspora-ai-visibility"
fi

# ---------------------------------------------------------------------------
# 4. Show what's about to land
# ---------------------------------------------------------------------------

echo ""
echo "==> Showing what's about to be committed"
cd "$CLONE_DIR"
git status seo-pilot-site/
echo ""
git --no-pager diff --stat -- seo-pilot-site/ || true

# ---------------------------------------------------------------------------
# 5. Stage, commit, push
# ---------------------------------------------------------------------------

echo ""
echo "==> Staging + committing"
git add seo-pilot-site/

# If there's nothing to commit (e.g. re-run), exit gracefully
if git diff --cached --quiet; then
  echo "    Nothing to commit — already up to date."
  exit 0
fi

git commit -m "$COMMIT_MSG"

echo ""
echo "==> Pushing to origin/$BRANCH"
git push origin "$BRANCH"

echo ""
echo "==> Done. View on GitHub:"
echo "    https://github.com/Admin0TSP/the-seo-pilot-site/tree/main/seo-pilot-site"
echo ""
echo "Next step (one-time): set CONTENTFUL_SPACE_ID + CONTENTFUL_ACCESS_TOKEN"
echo "in .env, then run 'npm run generate' to build the blog + case studies"
echo "into the live folders. The placeholder pages stay until you do."
